Repository On-derDog/TadakTadak, pull requests merged in 2024-01, with the labels that each got.

#5 feat/issue-2
  backend/discovery-service/.gitignore
  backend/discovery-service/build.gradle
  backend/discovery-service/gradle/wrapper/gradle-wrapper.jar
  backend/discovery-service/gradle/wrapper/gradle-wrapper.properties
  backend/discovery-service/gradlew
  backend/discovery-service/gradlew.bat
  backend/discovery-service/settings.gradle
  backend/discovery-service/src/main/java/com/tadak/discoveryservice/DiscoveryServiceApplication.java
  backend/discovery-service/src/main/resources/application.properties
  backend/discovery-service/src/test/java/com/tadak/discoveryservice/DiscoveryServiceApplicationTests.java
Labels: BE, Environment, 우선 순위 : 상

#6 Feat: eureka 서버 등록
  backend/discovery-service/build.gradle
  backend/discovery-service/src/main/java/com/tadak/discoveryservice/DiscoveryServiceApplication.java
  backend/discovery-service/src/main/resources/application.properties
  backend/discovery-service/src/main/resources/application.yml
Labels: BE, Feature, 우선 순위 : 상

#9 Feat: apigateway 설정
  backend/apigatewayservice/.gitignore
  backend/apigatewayservice/build.gradle
  backend/apigatewayservice/gradle/wrapper/gradle-wrapper.jar
  backend/apigatewayservice/gradle/wrapper/gradle-wrapper.properties
  backend/apigatewayservice/gradlew
  backend/apigatewayservice/gradlew.bat
  backend/apigatewayservice/settings.gradle
  backend/apigatewayservice/src/main/java/com/tadak/apigatewayservice/ApigatewayserviceApplication.java
  backend/apigatewayservice/src/main/resources/application.yml
  backend/apigatewayservice/src/test/java/com/tadak/apigatewayservice/ApigatewayserviceApplicationTests.java
Labels: BE, Feature, 우선 순위 : 상

#13 Feat/issue-1
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.prettierrc.json
  frontend/README.md
  frontend/index.html
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/public/vite.svg
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: ✨ Feature, 📦 Environment, 🧑‍💻 FE, 우선 순위 : 상

#15 feat/issue-14
  backend/user-service/.gitignore
  backend/user-service/build.gradle
  backend/user-service/gradle/wrapper/gradle-wrapper.jar
  backend/user-service/gradle/wrapper/gradle-wrapper.properties
  backend/user-service/gradlew
  backend/user-service/gradlew.bat
  backend/user-service/settings.gradle
  backend/user-service/src/main/java/com/tadak/userservice/UserServiceApplication.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/controller/UserController.java
  backend/user-service/src/main/resources/application.yml
  backend/user-service/src/test/java/com/tadak/userservice/UserServiceApplicationTests.java
Labels: 🧑‍💻 BE, ✨ Feature, 우선 순위 : 상

#25 feat/issue 16
  .idea/TadakTadak.iml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  frontend/src/App.tsx
  frontend/src/components/auth/auth.tsx
  frontend/src/components/chat/Chat.tsx
  frontend/src/components/chattingRoomList/ChattingRoomList.tsx
  frontend/src/components/layout/Layout.tsx
  frontend/src/components/video/Video.tsx
  frontend/src/hooks/Hook.ts
  frontend/src/pages/ChattingListPage.tsx
  frontend/src/pages/ChattingRoomPage.tsx
  frontend/src/pages/ErrorPage.tsx
  frontend/src/pages/RootPage.tsx
  frontend/src/pages/SigninPage.tsx
  frontend/src/pages/SignupPage.tsx
  frontend/src/pages/WelcomePage.tsx
  frontend/src/stores/Store.ts
  frontend/src/styles/Style.tsx
Labels: 📦 Environment, 🧑‍💻 FE, 우선 순위 : 상

#38 Feat/issue-29
  .idea/TadakTadak.iml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  frontend/src/App.tsx
  frontend/src/components/auth/auth.tsx
  frontend/src/components/chat/Chat.tsx
  frontend/src/components/chat/ChatForm.tsx
  frontend/src/components/chat/ChatRecent.tsx
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/chattingRoomList/ChattingRoomList.tsx
  frontend/src/components/layout/Layout.tsx
  frontend/src/components/video/Video.tsx
  frontend/src/hooks/Hook.ts
  frontend/src/pages/ChattingListPage.tsx
  frontend/src/pages/ChattingRoomPage.tsx
  frontend/src/pages/ErrorPage.tsx
  frontend/src/pages/RootPage.tsx
  frontend/src/pages/SigninPage.tsx
  frontend/src/pages/SignupPage.tsx
  frontend/src/pages/WelcomePage.tsx
  frontend/src/stores/Store.ts
  frontend/src/stores/useChatStore.ts
  frontend/src/styles/Style.tsx
  frontend/src/test/TestPage.tsx
Labels: ✨ Feature, 🧑‍💻 FE, 우선 순위 : 상, ✅ TestCode, 🚚 Rename

#41 Feat/issue-39
  backend/chatting-service/.gitignore
  backend/chatting-service/build.gradle
  backend/chatting-service/gradle/wrapper/gradle-wrapper.jar
  backend/chatting-service/gradle/wrapper/gradle-wrapper.properties
  backend/chatting-service/gradlew
  backend/chatting-service/gradlew.bat
  backend/chatting-service/settings.gradle
  backend/chatting-service/src/main/java/com/example/chattingservice/ChattingServiceApplication.java
  backend/chatting-service/src/main/java/com/example/chattingservice/domain/chat/controller/ChatController.java
  backend/chatting-service/src/main/java/com/example/chattingservice/domain/chat/dto/request/ChatRequest.java
  backend/chatting-service/src/main/java/com/example/chattingservice/domain/chat/dto/request/MessageType.java
  backend/chatting-service/src/main/java/com/example/chattingservice/domain/chat/dto/response/ChatResponse.java
  backend/chatting-service/src/main/java/com/example/chattingservice/global/config/WebSocketConfig.java
  backend/chatting-service/src/main/java/com/example/chattingservice/global/config/WebSocketEventListener.java
  backend/chatting-service/src/main/resources/application.yml
  backend/chatting-service/src/test/java/com/example/chattingservice/ChattingServiceApplicationTests.java
Labels: 🧑‍💻 BE, ✨ Feature, 우선 순위 : 상

#32 Feat/issue-17
  backend/user-service/build.gradle
  backend/user-service/src/main/java/com/tadak/userservice/UserServiceApplication.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/controller/UserController.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/controller/UserController.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/dto/request/LoginRequestDto.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/dto/request/SignupRequestDto.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/dto/response/DuplicateCheckResponseDto.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/dto/response/SignupResponseDto.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/dto/response/TokenResponseDto.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/entity/Member.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/entity/Role.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/entity/State.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/exception/DuplicateMemberEmailException.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/exception/DuplicateMemberUsernameException.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/exception/MemberStateException.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/exception/NotFoundMemberException.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/exception/NotMatchLogoutException.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/exception/NotMatchPasswordException.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/repository/MemberRepository.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/service/MemberService.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/refresh/entity/RefreshToken.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/refresh/repository/RefreshTokenRepository.java
  backend/user-service/src/main/java/com/tadak/userservice/global/error/ErrorCode.java
  backend/user-service/src/main/java/com/tadak/userservice/global/error/ErrorResponse.java
  backend/user-service/src/main/java/com/tadak/userservice/global/error/GlobalExceptionHandler.java
  backend/user-service/src/main/java/com/tadak/userservice/global/error/common/BusinessException.java
  backend/user-service/src/main/java/com/tadak/userservice/global/jwt/config/JwtSecurityConfig.java
  backend/user-service/src/main/java/com/tadak/userservice/global/jwt/exception/NotFoundTokenException.java
  backend/user-service/src/main/java/com/tadak/userservice/global/jwt/filter/JwtFilter.java
  backend/user-service/src/main/java/com/tadak/userservice/global/jwt/handler/JwtAccessDeniedHandler.java
  backend/user-service/src/main/java/com/tadak/userservice/global/jwt/handler/JwtAuthenticationEntryPoint.java
  backend/user-service/src/main/java/com/tadak/userservice/global/jwt/provider/TokenProvider.java
  backend/user-service/src/main/java/com/tadak/userservice/global/p6spy/P6SpySqlFormatter.java
  backend/user-service/src/main/java/com/tadak/userservice/global/redis/config/RedisConfig.java
  backend/user-service/src/main/java/com/tadak/userservice/global/security/config/CorsConfig.java
  backend/user-service/src/main/java/com/tadak/userservice/global/security/config/SecurityConfig.java
  backend/user-service/src/main/java/com/tadak/userservice/global/security/userdetail/CustomUserDetailsService.java
  backend/user-service/src/main/resources/application.yml
Labels: 🧑‍💻 BE, ✨ Feature, 우선 순위 : 상

#48 Feat/issue-22
  backend/chatting-service/src/main/resources/static/css/main.css
  backend/chatting-service/src/main/resources/static/index.html
  backend/chatting-service/src/main/resources/static/js/main.js
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/chat/ChatForm.tsx
  frontend/vite.config.ts
Labels: ✨ Feature, 🧑‍💻 FE, ALL, 우선 순위 : 상, ✅ TestCode, 👽 API
