Repository On-derDog/TadakTadak, pull requests merged in 2024-02, with the labels that each got.

#50 Feat/issue-47
  backend/user-service/.gitignore
  backend/user-service/build.gradle
  backend/user-service/src/main/java/com/tadak/userservice/domain/email/controller/EmailController.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/email/dto/EmailRequestDto.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/email/dto/EmailResponseDto.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/email/repository/EmailRepository.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/email/service/EmailService.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/controller/MemberController.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/dto/request/SignupRequestDto.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/dto/response/CheckEmailResponseDto.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/dto/response/TokenResponseDto.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/exception/EmailNotVerifiedException.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/service/MemberService.java
  backend/user-service/src/main/java/com/tadak/userservice/global/error/ErrorCode.java
  backend/user-service/src/main/java/com/tadak/userservice/global/jwt/provider/TokenProvider.java
  backend/user-service/src/main/java/com/tadak/userservice/global/security/config/CorsConfig.java
  backend/user-service/src/main/java/com/tadak/userservice/global/security/config/SecurityConfig.java
  backend/user-service/src/main/resources/application.yml
Labels: 🧑‍💻 BE, ✨ Feature, 우선 순위 : 상, 🚑 !HOTFIX

#57 Feat/issue-53
  --header
  --request
  --verbose
  frontend/.eslintrc.json
  frontend/.prettierrc.json
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/chat/Chat.tsx
  frontend/src/components/chat/ChatForm.tsx
  frontend/src/stores/useChatStore.ts
Labels: 🐛 BugFix, 🧑‍💻 FE, ALL, 우선 순위 : 상, ♻️ Refactoring, 🔧 Chore

#59 Feat-issue 58
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/service/MemberService.java
  backend/user-service/src/main/java/com/tadak/userservice/global/security/userdetail/CustomUserDetailsService.java
Labels: 🧑‍💻 BE, 우선순위 : 중, 🚑 !HOTFIX

#52 Feat/issue-42
  backend/chatting-service/.gitignore
  backend/chatting-service/build.gradle
  backend/chatting-service/src/main/java/com/example/chattingservice/domain/chat/controller/ChatController.java
  backend/chatting-service/src/main/java/com/example/chattingservice/domain/chat/dto/request/ChatRequest.java
  backend/chatting-service/src/main/java/com/example/chattingservice/domain/chat/dto/response/ChatListResponse.java
  backend/chatting-service/src/main/java/com/example/chattingservice/domain/chat/dto/response/ChatResponse.java
  backend/chatting-service/src/main/java/com/example/chattingservice/domain/chat/dto/response/ChatsResponse.java
  backend/chatting-service/src/main/java/com/example/chattingservice/domain/chat/entity/Chat.java
  backend/chatting-service/src/main/java/com/example/chattingservice/domain/chat/exception/NotFoundChatListException.java
  backend/chatting-service/src/main/java/com/example/chattingservice/domain/chat/exception/NotSaveChatException.java
  backend/chatting-service/src/main/java/com/example/chattingservice/domain/chat/exception/validation/Validation.java
  backend/chatting-service/src/main/java/com/example/chattingservice/domain/chat/repository/ChatRepository.java
  backend/chatting-service/src/main/java/com/example/chattingservice/domain/chat/service/ChatService.java
  backend/chatting-service/src/main/java/com/example/chattingservice/domain/chat/service/ChatServiceImpl.java
  backend/chatting-service/src/main/java/com/example/chattingservice/global/error/ErrorCode.java
  backend/chatting-service/src/main/java/com/example/chattingservice/global/error/ErrorResponse.java
  backend/chatting-service/src/main/java/com/example/chattingservice/global/error/GlobalExceptionHandler.java
  backend/chatting-service/src/main/java/com/example/chattingservice/global/error/common/BusinessException.java
Labels: 🧑‍💻 BE, ✨ Feature, 우선 순위 : 상

#60 feat/issue-19
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/video/VideoCall.tsx
  frontend/src/components/video/WebSock.tsx
Labels: ✨ Feature, 🧑‍💻 FE, 우선 순위 : 상

#64 feat/issue-20
  frontend/src/components/video/VideoCall.tsx
Labels: ✨ Feature, 🧑‍💻 FE, ALL, 우선 순위 : 상, 👽 API

#73 Feat/issue-27
  frontend/src/App.tsx
  frontend/src/components/chat/ChatForm.tsx
  frontend/src/components/chat/ChatMessage.tsx
  frontend/src/components/chat/ChatRecent.tsx
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/interface/ChatInterface.ts
  frontend/src/pages/ChattingRoomPage.tsx
  frontend/src/stores/useChatStore.ts
  frontend/src/test/TestPage.tsx
Labels: ✨ Feature, 💄 Design, 🧑‍💻 FE, ♻️ Refactoring, 🔧 Chore

#75 Feat/issue-74
  frontend/src/components/chat/ChatMessage.tsx
Labels: 🐛 BugFix, 🧑‍💻 FE, ♻️ Refactoring, 🔧 Chore

#35 Feat/issue-31
  frontend/.gitignore
  frontend/index.html
  frontend/src/App.tsx
  frontend/src/components/Button.tsx
  frontend/src/components/InputForm.tsx
  frontend/src/components/auth/NaverLoginButton.tsx
  frontend/src/hooks/useAuthQuery.ts
  frontend/src/pages/SigninPage.tsx
  frontend/src/pages/Signupnaver.tsx
  frontend/src/stores/UserInfoStore.ts
  frontend/tsconfig.json
Labels: ✨ Feature, 📦 Environment, 💄 Design, 🧑‍💻 FE, 우선 순위 : 상, 🔧 Chore

#44 Feat/issue-24
  frontend/src/components/chattingRoomList/ChattingRoom.tsx
  frontend/src/components/chattingRoomList/ChattingRoomList.tsx
  frontend/src/pages/ChattingListPage.tsx
Labels: ✨ Feature, 💄 Design, 🧑‍💻 FE, 우선 순위 : 상, 👽 API

#43 Feat/issue-33
  frontend/src/App.tsx
  frontend/src/pages/SignupPage.tsx
Labels: ✨ Feature, 💄 Design, 🧑‍💻 FE, 우선 순위 : 상, 👽 API

#62 Feat/issue-54
  backend/apigateway-service/.gitignore
  backend/apigateway-service/build.gradle
  backend/apigateway-service/src/main/java/com/tadak/apigatewayservice/config/CORSConfig.java
  backend/apigateway-service/src/main/java/com/tadak/apigatewayservice/filter/AuthFilter.java
  backend/apigateway-service/src/main/resources/application.yml
Labels: 🧑‍💻 BE, ✨ Feature, 우선 순위 : 상

#68 Feat/issue-67
  backend/user-service/build.gradle
  backend/user-service/src/main/java/com/tadak/userservice/global/oauth/CustomOAuth2UserService.java
  backend/user-service/src/main/java/com/tadak/userservice/global/oauth/OAuth2CustomMember.java
  backend/user-service/src/main/java/com/tadak/userservice/global/oauth/OAuth2MemberSuccessHandler.java
  backend/user-service/src/main/java/com/tadak/userservice/global/oauth/OAuthAttributes.java
  backend/user-service/src/main/java/com/tadak/userservice/global/security/config/SecurityConfig.java
Labels: 🧑‍💻 BE, ✨ Feature, 우선순위 : 중

#80 Feat/issue-76
  frontend/src/assets/Create.svg
  frontend/src/assets/Home.svg
  frontend/src/assets/Logo.svg
  frontend/src/assets/Logout.svg
  frontend/src/assets/Search.svg
  frontend/src/assets/Star.svg
  frontend/src/assets/react.svg
  frontend/src/components/Favorite.tsx
  frontend/src/components/Search.tsx
  frontend/src/components/Sidebar.tsx
  frontend/src/pages/WelcomePage.tsx
  frontend/src/styles/GlobalStyle.ts
Labels: ✨ Feature, 💄 Design, 🧑‍💻 FE, 우선 순위 : 상

#87 Feat/issue-85
  backend/chatroom-service/.gitignore
  backend/chatroom-service/build.gradle
  backend/chatroom-service/gradle/wrapper/gradle-wrapper.jar
  backend/chatroom-service/gradle/wrapper/gradle-wrapper.properties
  backend/chatroom-service/gradlew
  backend/chatroom-service/gradlew.bat
  backend/chatroom-service/settings.gradle
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/ChatroomServiceApplication.java
  backend/chatroom-service/src/main/resources/application.yml
  backend/chatroom-service/src/test/java/com/tadak/chatroomservice/ChatroomServiceApplicationTests.java
Labels: 🧑‍💻 BE, ✨ Feature, 우선 순위 : 상

#93 Feat/issue-88
  frontend/src/components/chat/Chat.tsx
  frontend/src/components/chat/ChatForm.tsx
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/user/List.tsx
  frontend/src/components/user/UserList.tsx
  frontend/src/components/user/UserProfile.tsx
  frontend/src/interface/CommonInterface.ts
  frontend/src/interface/UserListInterface.ts
  frontend/src/pages/ChattingRoomPage.tsx
  frontend/src/stores/useUserListStore.ts
  frontend/src/styles/ComponentLayout.ts
  frontend/src/styles/Layout.ts
Labels: 💄 Design, 🧑‍💻 FE, 우선 순위 : 상, ✅ TestCode

#91 Feat/issue-83
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/dto/response/TokenResponseDto.java
  backend/user-service/src/main/java/com/tadak/userservice/global/jwt/provider/TokenProvider.java
  backend/user-service/src/main/java/com/tadak/userservice/global/oauth/OAuth2MemberSuccessHandler.java
  backend/user-service/src/main/java/com/tadak/userservice/global/oauth/OAuthAttributes.java
  backend/user-service/src/main/resources/application.yml
Labels: 🧑‍💻 BE, ✨ Feature, 우선순위 : 중

#99 Feat/issue-96
  frontend/src/components/auth/NaverLoginButton.tsx
Labels: ✨ Feature, 🧑‍💻 FE, 우선 순위 : 상

#97 Feat/issue-95
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/controller/MemberController.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/dto/response/MemberResponseDto.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/service/MemberService.java
Labels: 🧑‍💻 BE, ✨ Feature, 우선 순위 : 상

#104 Feat/issue-94
  frontend/src/components/chat/ChatForm.tsx
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/user/List.tsx
  frontend/src/components/user/UserList.tsx
  frontend/src/components/user/UserProfile.tsx
  frontend/src/hooks/react-query/useUserData.ts
  frontend/src/interface/UserListInterface.ts
  frontend/src/pages/ChattingRoomPage.tsx
  frontend/src/styles/Layout.ts
Labels: ✨ Feature, 🧑‍💻 FE, ALL, 우선 순위 : 상, ♻️ Refactoring, ✅ TestCode, 💬 Pending, 👽 API

#106 feat/issue-105
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/dto/response/TokenResponseDto.java
  backend/user-service/src/main/java/com/tadak/userservice/domain/member/service/MemberService.java
Labels: 🧑‍💻 BE, 우선순위 : 중, 🚑 !HOTFIX

#103 Feat/issue-101
  frontend/src/assets/Email.svg
  frontend/src/assets/Password.svg
  frontend/src/assets/TadakTadak.svg
  frontend/src/assets/User.svg
  frontend/src/components/Button.tsx
  frontend/src/components/InputForm.tsx
  frontend/src/components/Toast.tsx
  frontend/src/components/auth/NaverLoginButton.tsx
  frontend/src/hooks/useAuthQuery.ts
  frontend/src/pages/SigninPage.tsx
  frontend/src/pages/SignupPage.tsx
Labels: ✨ Feature, 💄 Design, 🧑‍💻 FE, 우선순위 : 중

#108 Feat/issue-107
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/chat/ChatForm.tsx
  frontend/src/components/chat/ChatMessage.tsx
  frontend/src/components/user/UserProfile.tsx
  frontend/src/hooks/react-query/useUserData.ts
  frontend/src/pages/ChattingRoomPage.tsx
  frontend/src/stores/useChatStore.ts
Labels: 🐛 BugFix, ✨ Feature, 🧑‍💻 FE, 우선 순위 : 상

#110 Feat/issue-109
  frontend/src/hooks/useAuthQuery.ts
  frontend/src/pages/SigninPage.tsx
Labels: 🐛 BugFix, 🧑‍💻 FE, 우선 순위 : 상

#92 Feat/issue-90
  backend/chatroom-service/build.gradle
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatmember/dto/response/EnterChatMemberResponse.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatmember/entity/ChatMember.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatmember/entity/ChatMemberType.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatmember/repository/ChatMemberRepository.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatmember/service/ChatMemberService.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/controller/ChatRoomController.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/dto/request/ChatRoomRequest.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/dto/request/CreateChatroomRequest.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/dto/response/ChangeOwnerResponse.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/dto/response/ChatRoomResponse.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/dto/response/CreateChatroomResponse.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/dto/response/KickMemberResponse.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/entity/ChatRoom.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/exception/AlreadyKickedException.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/exception/CannotTransferOwnershipException.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/exception/NotFoundChatMemberException.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/exception/NotFoundChatRoomException.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/exception/NotRoomOwnerException.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/repository/ChatRoomRepository.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/service/ChatRoomService.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/global/error/ErrorCode.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/global/error/ErrorResponse.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/global/error/GlobalExceptionHandler.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/global/error/common/BusinessException.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/global/p6spy/P6SpySqlFormatter.java
Labels: 🧑‍💻 BE, ✨ Feature, 우선 순위 : 상

#115 feat/issue-113
  backend/apigateway-service/src/main/java/com/tadak/apigatewayservice/filter/AuthFilter.java
  backend/apigateway-service/src/main/resources/application.yml
Labels: 🧑‍💻 BE, ✨ Feature, 우선 순위 : 상

#122 Feat: 채팅방 개별 조회 API
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatmember/dto/response/ChatMemberResponse.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/controller/ChatRoomController.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/dto/request/CreateChatroomRequest.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/dto/response/CreateChatroomResponse.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/dto/response/OneChatRoomResponse.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/entity/ChatRoom.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/service/ChatRoomService.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/global/config/CorsConfig.java
Labels: 🧑‍💻 BE, ✨ Feature, 우선 순위 : 상

#117 FE-feat/issue-100
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/global/CorsConfig.java
  frontend/src/assets/Close.svg
  frontend/src/components/InputForm.tsx
  frontend/src/components/auth/InputForm.tsx
  frontend/src/components/auth/auth.tsx
  frontend/src/components/chattingRoomList/ChattingRoom.tsx
  frontend/src/components/chattingRoomList/ChattingRoomList.tsx
  frontend/src/components/common/Button.tsx
  frontend/src/components/common/Toast.tsx
  frontend/src/components/roomPreview/CreateRoomPreview.tsx
  frontend/src/components/roomPreview/RoomPreview.tsx
  frontend/src/components/roomPreview/RoomPreviewList.tsx
  frontend/src/components/welcome/Favorite.tsx
  frontend/src/components/welcome/Search.tsx
  frontend/src/components/welcome/Sidebar.tsx
  frontend/src/hooks/useAuthQuery.ts
  frontend/src/hooks/useGetAllRoom.ts
  frontend/src/pages/ChattingListPage.tsx
  frontend/src/pages/SigninPage.tsx
  frontend/src/pages/SignupPage.tsx
  frontend/src/pages/WelcomePage.tsx
  frontend/src/stores/useRoomStore.ts
  frontend/src/styles/Layout.ts
Labels: ✨ Feature, 💄 Design, 🧑‍💻 FE, 우선 순위 : 상, 👽 API

#126 feat/issue-121
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/video/Video.tsx
  frontend/src/components/video/VideoBox.tsx
  frontend/src/components/video/VideoCall.tsx
  frontend/src/components/video/example.tsx
Labels: ✨ Feature, 🧑‍💻 FE, 우선 순위 : 상

#131 Feat/issue 130
  backend/.idea/.gitignore
  backend/.idea/backend.iml
  backend/.idea/misc.xml
  backend/.idea/modules.xml
  backend/.idea/vcs.xml
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/App.tsx
  frontend/src/components/chatRoomInfo/ChatRoomInfo.tsx
  frontend/src/components/chatRoomInfo/Member.tsx
  frontend/src/components/chatRoomInfo/RoomMember.tsx
  frontend/src/components/chatRoomInfo/RoomName.tsx
Labels: ✨ Feature, 🧑‍💻 FE, 우선 순위 : 상, ✅ TestCode

#118 Refactoring: token claim 이메일로 수정
  backend/user-service/src/main/java/com/tadak/userservice/global/oauth/CustomOAuth2UserService.java
  backend/user-service/src/main/java/com/tadak/userservice/global/oauth/OAuth2CustomMember.java
  backend/user-service/src/main/java/com/tadak/userservice/global/oauth/OAuth2MemberSuccessHandler.java
Labels: 🧑‍💻 BE, ✨ Feature, 우선순위 : 중, ♻️ Refactoring

#129 Feat/issue-112
  frontend/pnpm-lock.yaml
  frontend/src/components/chat/ChatForm.tsx
  frontend/src/components/chat/ChatMessage.tsx
  frontend/src/components/common/Toast.tsx
  frontend/src/components/user/List.tsx
  frontend/src/components/user/UserList.tsx
  frontend/src/components/user/UserProfile.tsx
  frontend/src/hooks/custom-hook/useLoginWebSocket.ts
  frontend/src/interface/ChatInterface.ts
  frontend/src/interface/UserListInterface.ts
  frontend/src/pages/ChattingRoomPage.tsx
  frontend/src/pages/WelcomePage.tsx
  frontend/src/stores/useUserListStore.ts
Labels: 🐛 BugFix, 🧑‍💻 FE, ALL, 우선 순위 : 상, ♻️ Refactoring, 🔨 Conflict, 🔧 Chore, 👽 API

#136 Fe feat/issue 132
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/chatRoomInfo/ChangeBtn.tsx
  frontend/src/components/chatRoomInfo/ChatRoomInfo.tsx
  frontend/src/components/chatRoomInfo/KickBtn.tsx
  frontend/src/components/chatRoomInfo/Member.tsx
  frontend/src/components/chatRoomInfo/RoomMember.tsx
  frontend/src/stores/RoomInfoStore.ts
Labels: ✨ Feature, 🧑‍💻 FE, 우선 순위 : 상, 👽 API

#134 Feat/issue-28
  frontend/src/assets/Bookmark.svg
  frontend/src/assets/DefaultUser.svg
  frontend/src/components/roomPreview/CreateRoomPreview.tsx
  frontend/src/components/roomPreview/RoomPreview.tsx
  frontend/src/components/roomPreview/RoomPreviewList.tsx
  frontend/src/components/welcome/Search.tsx
  frontend/src/hooks/react-query/useAuthQuery.ts
  frontend/src/hooks/react-query/useGetAllRoom.ts
  frontend/src/pages/SigninPage.tsx
  frontend/src/pages/SignupPage.tsx
  frontend/src/pages/WelcomePage.tsx
Labels: 🐛 BugFix, ✨ Feature, 💄 Design, 🧑‍💻 FE, 우선 순위 : 상, 👽 API

#139 Feat/issue-137
  frontend/src/components/chatRoomInfo/ChatRoomInfo.tsx
  frontend/src/components/chatRoomInfo/Member.tsx
  frontend/src/components/chatRoomInfo/RoomMember.tsx
  frontend/src/components/chatRoomInfo/RoomName.tsx
  frontend/src/stores/RoomInfoStore.ts
  frontend/src/stores/useRoomInfoStore.ts
Labels: ✨ Feature, 🧑‍💻 FE, 우선 순위 : 상, 👽 API

#143 Feat/issue 140
  frontend/src/components/chatRoomInfo/ChatRoomInfo.tsx
  frontend/src/components/chatRoomInfo/Member.tsx
  frontend/src/pages/ChattingRoomPage.tsx
Labels: 🧑‍💻 FE, ALL, 우선 순위 : 상, ✅ TestCode, 👽 API

#147 feat/issue-146
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatmember/service/ChatMemberService.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/dto/response/ChatRoomResponse.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/exception/OverParticipationException.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/global/error/ErrorCode.java
Labels: 🧑‍💻 BE, ✨ Feature, 우선 순위 : 상

#149 feat/issue-148
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatmember/service/ChatMemberService.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/controller/ChatRoomController.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/dto/response/ChatRoomInfoResponse.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/dto/response/ChatRoomNameResponse.java
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/service/ChatRoomService.java
Labels: 🧑‍💻 BE, ✨ Feature, 우선순위 : 중

#151 feat/issue-150
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/service/ChatRoomService.java
Labels: 🐛 BugFix, 🧑‍💻 BE, 우선 순위 : 상

#152 Feat/issue 145
  frontend/src/components/chatRoomInfo/ChangeBtn.tsx
  frontend/src/components/chatRoomInfo/ChatRoomInfo.tsx
  frontend/src/components/chatRoomInfo/Member.tsx
  frontend/src/components/chatRoomInfo/RoomMember.tsx
  frontend/src/components/chatRoomInfo/RoomName.tsx
  frontend/src/stores/useRoomInfoStore.ts
Labels: ✨ Feature, 💄 Design, 🧑‍💻 FE, ALL, 우선 순위 : 상, ✅ TestCode

#156 Feat/issue 154
  frontend/src/components/video/VideoBox.tsx
  frontend/src/components/video/VideoCall.tsx
  frontend/src/pages/VideoCallPage.tsx
Labels: ✨ Feature, 💄 Design, 🧑‍💻 FE, 우선 순위 : 상

#158 Hotfix: git ignore, mysql 추가
  backend/chatroom-service/.gitignore
  backend/chatting-service/build.gradle
Labels: 🧑‍💻 BE, 우선 순위 : 상, 🚑 !HOTFIX

#159 Feat/issue 128
  frontend/src/components/chatRoomInfo/ChatRoomInfo.tsx
  frontend/src/components/chatRoomInfo/RoomName.tsx
  frontend/src/components/video/AudioBtn.tsx
  frontend/src/components/video/VideoBox.tsx
  frontend/src/components/video/VideoBtn.tsx
  frontend/src/components/video/VideoCall.tsx
  frontend/src/pages/ChattingRoomPage.tsx
  frontend/src/pages/VideoCallPage.tsx
  frontend/src/stores/useVideoCallStore.ts
Labels: ✨ Feature, 💄 Design, 🧑‍💻 FE, 우선 순위 : 상, 👽 API

#161 Bug/issue-160
  backend/chatroom-service/src/main/java/com/tadak/chatroomservice/domain/chatroom/controller/ChatRoomController.java
Labels: 🐛 BugFix, 🧑‍💻 BE, 우선순위 : 중

#164 Fix/issue 163
  frontend/src/components/chatRoomInfo/ChatRoomInfo.tsx
  frontend/src/stores/useRoomInfoStore.ts
Labels: 🧑‍💻 FE, 우선 순위 : 상, 🚑 !HOTFIX, 👽 API

#166 Style/issue-165
  frontend/src/pages/ChattingRoomPage.tsx
Labels: 💄 Design, 🧑‍💻 FE, 우선 순위 : 상

#144 Feat/issue 141
  frontend/src/components/roomPreview/RoomPreview.tsx
  frontend/src/components/roomPreview/RoomPreviewSkeleton.tsx
Labels: ✨ Feature, 💄 Design, 🧑‍💻 FE, 우선순위 : 하
